name: "Diff service"
description: "Checks if service has been updated and runs specified scripts for that service"
inputs:
  services-root: # id of input
    description: "Location of services"
    required: true
    default: ""
  token: # id of input
    description: "Github token"
    required: true
outputs:
  affected-services: #id of output
    description: "Names of services affected"

runs:
  using: "node16"
  main: "index.js"
